# -*- coding: utf-8 -*-
""" MagPie-ML Tutorial PART 2
        @author: Martin Garaj
        #tested with: 
            Windows 10, Spyder 3.3.6, Python 3.7
        #version: 1.0
        
    (Please, read Tutorial part 1 first)
    
    Knowing the layout settings from Tutorial part 1, lets now obtain some 
    data using the MagPie-ML logger object.
"""

#%% Imports
import magpie_ml as mp
import time



#%% Lets define the layout 
#   Use the parameters that fits your keyboard from Tutorial part 1
layout = mp.layout( keyboardType='external', language='englishUS', qwerty=True,  shift_l_long=True,  enter_tall=True  )
#   If you need to do bind/rebind/unbind symbols, do it below this line:
#   For instance:
#layout.unbindSymbolFromButton('~', 'Tilde')
#layout.bindSymbolFromButton('\', 'Tilde')



### Create key logger
#   Since the logger needs to match the symbols to buttons, 
#   we need to provide a dictionary that translates symbols to buttons.
#   The dictionary is generated by the layout object.
#   Also, lets decide how the logger is stopped by a combination of 
#   "escapeButtons". Lets use LEFT CONTROL (Ctrl_l) and ESCAPE ('Esc') 
#   buttons, to stop the key logger and save the logged data.
logger = mp.logger( layout.getSymbolToButtonDict(), path='loggedData.txt', doNotLogButtons=[], escapeButtons=['Esc', 'Ctrl_l'], debug=True )
#   Start the logger
logger.start()

